---
#-------------------------------
# General Site Settings

title: HJ
logo:
author: themefisher
description: this is meta description
email: as9804@berkeley.edu
phone: +1 510 277 7727
address: Berkeley, CA 94705, USA
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: G-RLGZ1EZ0FB # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Hyunwook Jung <br> Software Developer

social:
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/hyunwook-jung-ucb0827/" }
#  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/hyunwook-jung-ucb0827/" }
#  - { icon: "ti-instagram", link: "#" }
#  - { icon: "ti-dribbble", link: "#" }
#  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: I am a software engineer with a passion for building innovative and user-friendly products. I have experience in a variety of programming languages and technologies, and I am always eager to learn new things. I am a highly motivated and results-oriented team player with a strong work ethic.

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
#work-process:
#  - title: "Research and Plan"
#    icon: "assets/images/icons/plan.png"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#  - title: "Design and Develop"
#    icon: "assets/images/icons/design.png"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#  - title: "Deliver"
#    icon: "assets/images/icons/print.png"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
#team:
#  - title: "Hyunwook Jung"
#    image: "assets/images/team/member-1.png"
#    designation: "Software Developer"

#  - title: "Julias Carlie"
#    image: "assets/images/team/member-2.png"
#    designation: "Web Developer"

#  - title: "John Doe"
#    image: "assets/images/team/member-3.png"
#    designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Efficient Algorithm/Theory, color: "#ffbcaa", value: "70%" }
  - { name: Problem Solving, color: "#fdb157", value: "90%" }
  - { name: Cloud Engineering, color: "#9473e6", value: "50%" }
  - { name: Machine Learning, color: "#bdecf6", value: "30%" }

#-------------------------------
# Exprerience Section

experience-title: Language
experience:
  - {
      name: PYTHON,
      icon: "icon-1.png",
      date: "2020 - 2023",
      #organization: "WEBEX",
    }
  - {
      name: C++,
      icon: "icon-3.png",
      date: "2018 - 2020",
      #organization: "AUGMEDIX",
    }
  - {
      name: GoLang,
      icon: "icon-3.png",
      date: "2023 - 2023",
      #organization: "THEMEFISHER",
    }
  - {
      name: Java,
      icon: "icon-1.png",
      date: "2023 - 2023",
      #organization: "THEMEFISHER",
    }
  - {
      name: SQL,
      icon: "icon-2.png",
      date: "2020 - 2023",
      #organization: "THEMEFISHER",
    }
  - {
      name: Javascript,
      icon: "icon-2.png",
      date: "2020 - 2020",
      #organization: "THEMEFISHER",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: B.S Electrical Engineering & Computer Science,
      date: "2023",
      organization: "University of California, Berkeley",
    }
  - {
      name: A.S Computer Science and Python Programming,
      date: "2020",
      organization: "Diablo Valley College",
    }
  - {
      name: A.S Computer Software Engineering,
      date: "2020",
      organization: "Diablo Valley College",
    }
  

#-------------------------------
# Services Section

#services-title: Services
#services:
#  - {
#      name: UI Design,
#      icon: ti-palette,
#      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
#      active: ,# Add true to select section
#    }
#  - {
#      name: UX Design,
#      icon: ti-vector,
#      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
#      active: true, # Add true to select section
#    }
#  - {
#      name: Interaction Design,
#      icon: ti-panel,
#      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
#      active: ,# Add true to select section
#    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-button:
  label: Portfolio
  url: /portfolio

portfolio-home-items:
  - image: "assets/images/portfolio/go-cloud-storage-1.png"
    url: "https://github.com/HyunwookJung0827/Encrypted-File-Sharing-System"
    project-description: "This is aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

#  - image: "assets/images/portfolio/item-2.png"
#    url: "/about"
#    project-description: "This is a description of my second project."

#  - image: "assets/images/portfolio/item-3.png"
#    url: "/about"
#    project-description: "This is a description of my third project."

#  - image: "assets/images/portfolio/item-4.png"
#    url: "#"
#    project-description: "This is a description of my fourth project."

#  - image: "assets/images/portfolio/item-5.png"
#    url: "#"
#    project-description: "This is a description of my fifth project."

# Portfolio Page
portfolio-label:
  - { title: "Python", type: "Python" }
  - { title: "GoLang", type: "GoLang" }
  - { title: "Java", type: "Java" }
  - { title: "Machine Learning", type: "Machine Learning" }
  - { title: "Cloud Engineering", type: "Cloud Engineering" }

portfolio-items:
  - image: "assets/images/portfolio/Go-Storage.png"
    url: "https://github.com/HyunwookJung0827/Encrypted-File-Sharing-System"
    portfolio-type:
      - type: "GoLang"
      - type: "Cloud Engineering"
    project-description: "Built a secure online file sharing system that uses end-to-end encryption to protect user data. The system allows users to store, add, and load data in linear time, and uses linked lists to represent the original data with multiple updates. To prevent unauthorized access, the system uses public/private user keys for asymmetric/symmetric hashing of credential data, and generates different keys for different purposes by multiple hashing."

  - image: "assets/images/portfolio/Aries.jpg"
    url: "https://github.com/HyunwookJung0827/CS186-Database/tree/master/sp23-proj5-HyunwookJung0827-main"
    portfolio-type:
      - type: "Java"
    project-description: "Algorithm for Recovery and Isolation Exploiting Semantics"

#  - image: "assets/images/portfolio/item-3.png"
#    url: "/about"
#    portfolio-type:
#      - type: "illustration"
#    project-description: "This is a description of my eith project."

#  - image: "assets/images/portfolio/item-6.png"
#    url: "/about"
#    portfolio-type:
#      - type: "design"
#      - type: "branding"
#    project-description: "This is a description of my first project."

#  - image: "assets/images/portfolio/item-8.png"
#    url: "/about"
#    portfolio-type:
#      - type: "illustration"
#    project-description: "This is a description of my nineth project."

#  - image: "assets/images/portfolio/item-5.png"
#    url: "/about"
#    portfolio-type:
#      - type: "design"

#  - image: "assets/images/portfolio/item-1.png"
#    url: "#"
#    portfolio-type:
#      - type: "branding"
#    project-description: "This is a description of my tenth project."

#  - image: "assets/images/portfolio/item-3.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
#      - type: "illustration"
#      - type: "branding"
#    project-description: "This is a description of my 11th project."

#  - image: "assets/images/portfolio/item-7.png"
#    url: "#"
#    portfolio-type:
#      - type: "illustration"
#    project-description: "This is a description of my 12th project."


#-------------------------------
# Testimonials Section

#testimonial-items:
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section

#client-slider-items:
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: as9804@berkeley.edu


script: "function showProjectDescription(thumbnail) {
  #// Get the project description element.
  const projectDescription = thumbnail.querySelector('.project-description');

  #// Show the project description element.
  projectDescription.style.display = 'block';

  #// Add a listener to the thumbnail to hide the project description element when the mouse leaves the thumbnail.
  thumbnail.addEventListener('mouseleave', function() {
    projectDescription.style.display = 'none';
  });
}

#// Add a listener to each thumbnail to call the showProjectDescription() function when the user hovers their mouse over the thumbnail.
document.querySelectorAll('.portfolio-thumbnail').forEach(thumbnail => {
  thumbnail.addEventListener('mouseover', function() {
    showProjectDescription(thumbnail);
  });
});"
